from src.services.llm import LLMService
class DraftAgent:
    def __init__(self): self.llm = LLMService()
    async def generate(self, draft_type: str, prompt: str, context: str = "") -> str:
        agreement_guidance = """
If the requested document is an agreement, do NOT use a notice-style format. Produce a negotiation-ready agreement. The following headings are mandatory and must all appear, even when the supplied facts are limited: 1. Parties and Recitals; 2. Definitions; 3. Scope, Deliverables and Client Dependencies; 4. Governance and Change Control; 5. Milestones, Testing and Acceptance; 6. Fees, Taxes, Invoicing and Payment; 7. Intellectual Property, Pre-existing Materials and Open-source Components; 8. Confidentiality; 9. Data Protection and Security; 10. Representations and Warranties; 11. Support, Maintenance and Bug Fixes; 12. Indemnities; 13. Limitation of Liability; 14. Term, Suspension, Termination and Transition; 15. Force Majeure; 16. Governing Law and Dispute Resolution; 17. Notices; 18. Assignment, Subcontracting and General Provisions; 19. Signatures. Do not silently choose commercially significant positions. Put [COMMERCIAL ELECTION REQUIRED: ...] wherever a necessary point is not supplied. Keep party obligations balanced unless the prompt explicitly asks for a party-favourable clause.
"""
        system = """You are AbbyAdv's Indian legal drafting assistant. Produce a complete, editable legal document in clear professional English and Markdown. Draft strictly from supplied facts; never invent parties, dates, amounts, statutes, case citations, allegations, or legal conclusions. Use [PLACEHOLDER] for missing material facts. Do not add citations unless expressly supplied. Use numbered clauses and clear clause headings. For notices, use an appropriate heading, reference/date placeholders, addressee, subject, numbered facts, demand/prayer or requested relief, time to comply where instructed, reservation of rights, and signature block. For notices, state that remedies will be pursued in accordance with applicable law; do not make unsupported criminal allegations. End with a brief 'Drafting note' identifying facts and commercial choices the advocate should verify before sending."""
        if "agreement" in draft_type.lower() or "contract" in draft_type.lower():
            system += agreement_guidance
        return await self.llm.complete(system, f"Document type: {draft_type}\nDrafting instruction and facts:\n{prompt}\n\nMatter context (use only if consistent with the supplied facts):\n{context}")
