import { AlertTriangle, ArrowRight, ArrowUpRight, CalendarClock, CheckCircle2, Clock3, FileClock, FileText, Plus, Scale, ShieldAlert, Sparkles, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import { ReactNode, useEffect, useState } from 'react';
import { apiFetch } from '../lib/api';

type FocusItem = { id: string; title: string; description?: string | null; priority: string; due_date?: string | null; case_id?: string | null; case_name?: string | null };
type UpcomingEvent = { id: string; title: string; event_type: string; event_date?: string | null; severity: string; case_id?: string | null; case_name?: string | null };
type Matter = { id: string; case_name: string; client_name: string; matter_type: string; stage?: string | null; risk_level: string; next_hearing_date?: string | null; limitation_date?: string | null; document_count: number };
type Activity = { kind: 'draft' | 'scenario' | 'case'; title: string; detail: string; date: string; case_id?: string | null };
type Summary = { total_clients: number; active_cases: number; hearings_this_week: number; critical_action_items: number; pending_drafts: number; pending_document_processing: number; documents_ready: number; completed_scenarios: number; focus_items: FocusItem[]; upcoming_events: UpcomingEvent[]; matter_snapshot: Matter[]; recent_activity: Activity[] };

const humanize = (value?: string | null) => (value || 'Not set').replace(/_/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
const friendlyDate = (value?: string | null) => value ? new Intl.DateTimeFormat('en-IN', { day: 'numeric', month: 'short' }).format(new Date(`${value}T12:00:00`)) : 'Date to confirm';
const dayLabel = () => new Intl.DateTimeFormat('en-IN', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }).format(new Date());

export default function DashboardPage() {
  const [summary, setSummary] = useState<Summary | null>(null);
  useEffect(() => { apiFetch<Summary>('/api/dashboard/summary').then(setSummary).catch(() => setSummary(null)); }, []);
  const cards = [
    ['Active matters', summary?.active_cases, summary?.active_cases ? 'Matters currently moving' : 'Create a matter to get started', BriefcaseIcon],
    ['Clients', summary?.total_clients, summary?.total_clients ? 'Your active client portfolio' : 'Build your client workspace', Users],
    ['Hearings this week', summary?.hearings_this_week, summary?.hearings_this_week ? 'Court dates that need preparation' : 'No hearings scheduled this week', CalendarClock],
    ['Needs attention', summary?.critical_action_items, summary?.critical_action_items ? 'Priority case actions need review' : 'Your priority queue is clear', ShieldAlert],
  ] as const;
  const queueItems = [
    { icon: FileClock, tone: 'amber', title: `${summary?.pending_document_processing ?? 0} documents processing`, detail: summary?.pending_document_processing ? 'ABBYY extraction and indexing in progress' : `${summary?.documents_ready ?? 0} documents ready for case-aware work` },
    { icon: Sparkles, tone: 'indigo', title: `${summary?.completed_scenarios ?? 0} scenario analyses ready`, detail: summary?.completed_scenarios ? 'Review strengths, risks and next steps' : 'Run a scenario from any active matter' },
    { icon: CheckCircle2, tone: 'green', title: `${summary?.pending_drafts ?? 0} drafts in progress`, detail: summary?.pending_drafts ? 'Continue refining legal work product' : 'Start a notice, reply, agreement or review' },
  ];
  return <div className="dashboard">
    <div className="page-heading"><div><p className="eyebrow">{dayLabel()}</p><h1>Good morning, Advocate.</h1><p className="muted">Here is the pulse of your practice today.</p></div><Link to="/clients" className="primary-button"><Plus size={17}/> Add client</Link></div>
    <section className="stat-grid">{cards.map(([label, value, detail, Icon]) => <div className="stat-card" key={label}><div className="stat-icon"><Icon size={19}/></div><span>{label}</span><strong>{summary ? value : '—'}</strong><small>{detail}</small></div>)}</section>
    <div className="dashboard-grid"><section className="welcome-card"><div><p className="eyebrow light">CASE INTELLIGENCE</p><h2>{summary?.active_cases ? `${summary.active_cases} matters,` : 'Everything important,'}<br/><em>{summary?.critical_action_items ? `${summary.critical_action_items} need your attention.` : 'closer at hand.'}</em></h2><p>Ask AbbyAdv about a case, find a document, or turn your next thought into a draft.</p><Link to="/chat" className="light-button">Open AI workspace <ArrowUpRight size={16}/></Link></div><div className="orb"><div className="orb-inner">A</div></div></section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Your queue</p><h3>What needs your attention</h3></div><Link to="/clients" className="ghost-link">View matters <ArrowUpRight size={14}/></Link></div>{queueItems.map((item) => <div className="queue-row" key={item.title}><div className={`queue-icon ${item.tone}`}><item.icon size={17}/></div><div><b>{item.title}</b><span>{item.detail}</span></div><ArrowUpRight size={16} className="row-arrow"/></div>)}</section></div>
    <section className="dashboard-live-grid">
      <section className="panel dashboard-matters"><div className="panel-heading"><div><p className="eyebrow">MATTER HEALTH</p><h3>Active case snapshot</h3></div><Link to="/clients" className="ghost-link">All clients <ArrowRight size={14}/></Link></div>{summary?.matter_snapshot.length ? <div className="dashboard-list">{summary.matter_snapshot.map((matter) => <Link className="dashboard-matter" to={`/cases/${matter.id}`} key={matter.id}><div className="dashboard-matter-icon"><Scale size={17}/></div><div><b>{matter.case_name}</b><span>{matter.client_name} · {humanize(matter.matter_type)}</span><small>{matter.next_hearing_date ? `Next hearing ${friendlyDate(matter.next_hearing_date)}` : matter.limitation_date ? `Limitation ${friendlyDate(matter.limitation_date)}` : `${matter.document_count} supporting documents`}</small></div><i className={`risk-dot ${matter.risk_level}`}/></Link>)}</div> : <EmptyDash icon={<Scale size={20}/>} text="Create a client and matter to see case health here." link="/clients" action="Add a client"/>}</section>
      <section className="panel dashboard-focus"><div className="panel-heading"><div><p className="eyebrow">TODAY'S FOCUS</p><h3>Priority work</h3></div><AlertTriangle size={17} className="focus-icon"/></div>{summary?.focus_items.length ? <div className="dashboard-list">{summary.focus_items.map((item) => <Link className="dashboard-focus-item" to={item.case_id ? `/cases/${item.case_id}` : '/clients'} key={item.id}><span className={`priority-pill ${item.priority}`}>{item.priority}</span><div><b>{item.title}</b><small>{item.case_name || 'Practice task'}{item.due_date ? ` · Due ${friendlyDate(item.due_date)}` : ''}</small></div></Link>)}</div> : <EmptyDash icon={<CheckCircle2 size={20}/>} text="No urgent actions right now. Use scenario analysis to surface next steps." link="/clients" action="Open a matter"/>}</section>
      <section className="panel dashboard-schedule"><div className="panel-heading"><div><p className="eyebrow">UPCOMING</p><h3>Schedule & hearings</h3></div><CalendarClock size={17} className="focus-icon"/></div>{summary?.upcoming_events.length ? <div className="dashboard-list">{summary.upcoming_events.map((event) => <Link className="dashboard-event" to={event.case_id ? `/cases/${event.case_id}` : '/clients'} key={event.id}><time><b>{new Date(`${event.event_date}T12:00:00`).getDate()}</b><span>{new Intl.DateTimeFormat('en-IN', { month: 'short' }).format(new Date(`${event.event_date}T12:00:00`))}</span></time><div><b>{event.title}</b><small>{event.case_name || humanize(event.event_type)} · {humanize(event.event_type)}</small></div></Link>)}</div> : <EmptyDash icon={<CalendarClock size={20}/>} text="No dates are scheduled in the next 30 days." link="/clients" action="View matters"/>}</section>
    </section>
    <section className="panel dashboard-activity"><div className="panel-heading"><div><p className="eyebrow">PRACTICE ACTIVITY</p><h3>Recent work across your matters</h3></div><Clock3 size={17} className="focus-icon"/></div>{summary?.recent_activity.length ? <div className="dashboard-activity-list">{summary.recent_activity.map((activity, index) => <Link to={activity.case_id ? `/cases/${activity.case_id}` : activity.kind === 'draft' ? '/drafts' : '/clients'} className="dashboard-activity-row" key={`${activity.kind}-${index}`}><span className={`activity-kind ${activity.kind}`}>{activity.kind === 'draft' ? <FileText size={14}/> : activity.kind === 'scenario' ? <Sparkles size={14}/> : <Scale size={14}/>}</span><div><b>{activity.title}</b><small>{activity.detail}</small></div><time>{new Intl.DateTimeFormat('en-IN', { day: 'numeric', month: 'short' }).format(new Date(activity.date))}</time></Link>)}</div> : <EmptyDash icon={<Sparkles size={20}/>} text="Your client, document and scenario activity will appear here." link="/clients" action="Start with a client"/>}</section>
  </div>;
}

function EmptyDash({ icon, text, link, action }: { icon: ReactNode; text: string; link: string; action: string }) { return <div className="dashboard-empty"><span>{icon}</span><p>{text}</p><Link to={link}>{action} <ArrowRight size={13}/></Link></div>; }
function BriefcaseIcon({ size }: { size?: number }) { return <span style={{ fontSize: size || 19 }}>◈</span>; }
